### ISSUE TITLE
该插件在版本 Obsidian 0.14.15中不起作用？

### ISSUE THREAD

**Issue by johnking** [ALONELUR/vim-im-select-obsidian#10]
我配置了插件，根据developer tools 窗口，可以看到， 每次切换mode时， 插件似乎调用了fcitx-remote -s {im}， 但是输入法却没有真正切换。

<img width="1212" alt="截屏2022-06-19 11 29 48" src="https://user-images.githubusercontent.com/1787137/174464658-6bea77df-cd77-48fc-a079-ac30924e3631.png">

但是我如果在terminal中用同样的命令手动切换，却可以成功。

<img width="968" alt="截屏2022-06-19 11 38 07" src="https://user-images.githubusercontent.com/1787137/174464798-426764f7-de1c-49a2-b486-69620adbfc16.png">

请问有什么建议可以解决这个问题吗？

谢谢

**Comment by johnking** [comment]
我尝试在法语和英语之间切换，plug-in的调试信息打印显示执行了命令，但实际上没有真正切换输入方法。同样，在terminal中手动敲命令，则可以有效地切换IM。

当前版本的obsidian使用的codeMirror版本是 6

**Comment by ALONELUR** [comment]
能贴出配置页面的配置吗

**Comment by johnking** [comment]
Sure！
---
- Default IM: keyboard-us
- obtaining command, tried two options
   - Option 1: im-select
   - option 2: [[ `/usr/local/bin/fcitx-remote` == 2 ]] && echo pinyin || echo keyboard-us
- switching command
   -  /usr/local/bin/fcitx-remote -s {im}
<img width="772" alt="截屏2022-06-21 10 08 31" src="https://user-images.githubusercontent.com/1787137/174701684-d0ce3bfa-246a-4c2c-a542-ca78429512e6.png">

---
I tried both CM5 and CM6 Editor, neither works for me.

**Comment by Rick1125** [comment]
@johnking fcitx-remote m1 可能需要自己编译，编译出来针对特定的输入法的可执行文件。
比如我用的是fcitx-remote-sogou-pinyin

**Comment by ALONELUR** [comment]
Have you try to execute ` [[ /usr/local/bin/fcitx-remote == 2 ]] && echo pinyin || echo keyboard-us` in terminal under pinyin IM and us IM?
