### ISSUE TITLE
m1 Mac使用im-select在obsidian中无法正常切换

### ISSUE THREAD

**Issue by RainGoal** [ALONELUR/vim-im-select-obsidian#13]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/60003677/180942938-b52b0fb4-a92c-414b-bea3-da93365bafda.png">
如图，已经在插件配置中配置了im-select
并且在终端中，可以使用im-select正常切换输入法
<img width="608" alt="image" src="https://user-images.githubusercontent.com/60003677/180943163-697cb226-52e7-4677-ba90-962df15365c0.png">
但是在obsidian中，如果从中文输入法模式退出到normal模式，依旧还是中文输入法

**Comment by RainGoal** [comment]
系统版本是Macos 12.5，且在vscode中，im-select正常工作，但是在obsidian中，没办法切换

**Comment by yizhenAllen** [comment]
M1 mac, 使用im-select时, 输入模式换为普通模式, 可以稳定地切换为英文输入法, 但是再次输入时, 无法记忆上一次输入时使用的输入法, 切换时很不稳定.

解决: 使用macism解决问题.

**Comment by betterZCH** [comment]
> M1 mac, 使用im-select时, 输入模式换为普通模式, 可以稳定地切换为英文输入法, 但是再次输入时, 无法记忆上一次输入时使用的输入法, 切换时很不稳定.
> 
> 解决: 使用macism解决问题.

我也用的mac，也用了macism，但是无法切换，可以看看你怎么写的命令吗？
