### ISSUE TITLE
打开第二个笔记时未正确切换语言

### ISSUE THREAD

**Issue by bushnerd** [ALONELUR/vim-im-select-obsidian#19]
# 问题复现步骤：
1. 打开某个笔记，此时处于Normal状态，那么当前的输入语言为1033
2. Ctrl+o打开另外一个笔记，i进入Insert模式，输入语言没有切换为2052，仍然是1033
3. Esc返回，仍然是1033，再i进入Insert模式，输入语言没有切换为2052，仍然是1033

# 问题如何避免
1. 打开某个笔记，此时处于Normal状态，那么当前的输入语言为1033
2. i进入Insert模式，输入语言顺利切换为2052
3. Insert模式下，Ctrl+o打开另外一个笔记，i进入Insert模式，输入语言顺利切换为2052

# 总结与分析
猜测在打开其他的笔记之前，会判断当前的语言，如果是在Normal模式下，则语言为1033，那么在打开其他笔记时，程序会认为返回Insert模式后，也应该切换为1033。

**Comment by ALONELUR** [comment]
0.2.0 已经修复了这个问题
