### ISSUE TITLE
不知道为什么开启之后特别卡顿

### ISSUE THREAD

**Issue by lifesign** [ALONELUR/vim-im-select-obsidian#2]
按 esc 切换的时候，就卡至少2s

![image](https://user-images.githubusercontent.com/2189610/148377409-f9877b6a-0b46-47e2-95cd-bb1c3b0e6d0c.png)

是使用的 im-select 的问题么，mac 平台

**Comment by sigma2647** [comment]
+1 mac 平台同样卡

**Comment by ALONELUR** [comment]
目前我手边没有mac系统的电脑，等我过几天找一台mac系统尝试一下。

不过目前就我在windows和linux下使用的条件来看，有可能是im-select本身的问题。

有试过单独使用im-select来更改输入法吗？是否有类似的卡顿

**Comment by sigma2647** [comment]
把 Switching Command 改为 im-select之后卡顿时间缓解,切换输入法成功,但在进行普通模式和插入模式切换时仍然会有1~2秒的延迟

这个是我尝试修改后的命令
<img width="889" alt="image" src="https://user-images.githubusercontent.com/61632637/148494706-4482d9f8-cfe4-4037-bf71-418177d45fc2.png">

**Comment by sigma2647** [comment]
切换输入法有效,但在进行普通模式和插入模式切换时仍然会有1~2秒的延迟甚至卡顿
在命令行使用如下命令切换成功无延迟
```
/usr/local/bin/im-select com.apple.keylayout.US
```

这个是我的配置
<img width="901" alt="image" src="https://user-images.githubusercontent.com/61632637/148494913-f6328a8a-e45e-49b7-bef8-67a18dac825a.png">

**Comment by sigma2647** [comment]
在终端的neovim中使用[smartim](https://github.com/ybian/smartim)这个插件是正常的,而在obsidian中使用另一款插件[obsidian-vim-im-switch-plugin](https://github.com/yuanotes/obsidian-vim-im-switch-plugin)同样会造成卡顿,不知道是否因为mac系统软件的机制导致不能及时与命令行交互导致的问题还是obsidian本身的问题.非常期待大佬能够解决,感激不尽!

**Comment by liang-0131** [comment]
同mac 并没有那么卡顿的情况

**Comment by sigma2647** [comment]
> 同mac 并没有那么卡顿的情况

请问你的mac版本是Monterey还是catalina呀

**Comment by liang-0131** [comment]
c 我以前用另一个插件也没有这种情况

**Comment by lilongthinker** [comment]
同样是卡顿问题，mac版本Monterey
im-select 单独执行命令海还是很快的

**Comment by sigma2647** [comment]
我看了下控制台这边开启插件的时候有个报错
<img width="496" alt="image" src="https://user-images.githubusercontent.com/61632637/149061219-295ca0f3-8329-465d-9cdd-fa19eb935858.png">

**Comment by ALONELUR** [comment]
> 我看了下控制台这边开启插件的时候有个报错 <img alt="image" width="496" src="https://user-images.githubusercontent.com/61632637/149061219-295ca0f3-8329-465d-9cdd-fa19eb935858.png">

这个报错不影响mac系统响应满的问题，这个BUG已经在0.1.1版本中修复了。

**Comment by ALONELUR** [comment]
目前经过我实验发现主要问题是生成子进程的过程导致了延迟。从生成子进程到完成全部要经过2.4秒，但脚本只执行了0.048秒。
![image](https://user-images.githubusercontent.com/46865464/149147857-7e78de21-4446-43b3-8e75-378375d95699.png)

我会再尝试不同的API配置以解决这个问题。

**Comment by cherrot** [comment]
我这不止卡顿，卡顿后输入法并没切换过来... 终端使用 im-select 可以正常切换，vim 也可以正常切换...

**Comment by ekilzen** [comment]
mac 同样有卡顿问题

**Comment by JMaxU** [comment]
mac 同样有卡顿问题

**Comment by ALONELUR** [comment]
目前mac平台下的卡顿，是因为唤起/bin/sh导致了卡顿，因为我本人没有mac的电脑，我正在找人借mac系统调试这个问题。如果有mac开发者知道为什么会有这个问题欢迎提出解决办法。

**Comment by matyle** [comment]
> 同样是卡顿问题，mac版本Monterey
> im-select 单独执行命令海还是很快的

vscodevim 也是使用im-select不存在卡顿 应该可以优化？

**Comment by matyle** [comment]
> 目前mac平台下的卡顿，是因为唤起/bin/sh导致了卡顿，因为我本人没有mac的电脑，我正在找人借mac系统调试这个问题。如果有mac开发者知道为什么会有这个问题欢迎提出解决办法。

可否尝试 唤起zsh？我试了下 使用zsh执行快捷指令的脚本 几乎调用无延迟

**Comment by ALONELUR** [comment]
> 可否尝试 唤起zsh？我试了下 使用zsh执行快捷指令的脚本 几乎调用无延迟

目前已经基本可以确定，导致延迟的是每次调用脚本时打开zsh的延迟，而不是im-select的延迟。
但是我目前也没有mac电脑，所以不太好解决这个问题，非常抱歉。
我的思路是，或许可以在运行起该插件时，运行一个交互式的zsh，在该交互式zsh中进行im-select的调用。如果有mac的开发者有办法实现这个思路的话非常欢迎对这个插件进行修改。

**Comment by matyle** [comment]
> > 可否尝试 唤起zsh？我试了下 使用zsh执行快捷指令的脚本 几乎调用无延迟
> 
> 目前已经基本可以确定，导致延迟的是每次调用脚本时打开zsh的延迟，而不是im-select的延迟。 但是我目前也没有mac电脑，所以不太好解决这个问题，非常抱歉。 我的思路是，或许可以在运行起该插件时，运行一个交互式的zsh，在该交互式zsh中进行im-select的调用。如果有mac的开发者有办法实现这个思路的话非常欢迎对这个插件进行修改。
可能是obsidian api的问题，我用了另外一个插件切换输入法 也存在卡顿现象

**Comment by matyle** [comment]
可能是obsidian api的问题，我用了另外一个插件切换输入法 也存在卡顿现象

**Comment by ALONELUR** [comment]
目前在Macbook上实验过后没有发现相关问题了，应该是Obsidian已经更新了API

**Comment by lifesign** [comment]
我今天测试了下 确实丝滑了~ 赞👍🏻
