### ISSUE TITLE
macOS 无法切换输入法

### ISSUE THREAD

**Issue by liulu1998** [ALONELUR/vim-im-select-obsidian#23]
## 问题

配置插件后，在 Vim Insert 模式中按下 Esc 键，并未切换为系统英文输入法； 在 Normal 模式进入 Insert 模式，也并未切换为搜狗输入法。

## 插件配置

- Default IM:  com.apple.keylayout.US
- Obtaining Command:  /opt/homebrew/bin/macism
- Switching Command：/opt/homebrew/bin/macism {im}

![image](https://github.com/ALONELUR/vim-im-select-obsidian/assets/48306835/6a8ae6ca-03bf-4403-b6d9-9a4497187771)

## 环境

操作系统：macOS 14.1.1，m1 芯片
Obsidian：1.4.16

中文使用搜狗输入法

**Comment by matyle** [comment]
同，m1 14系统切换不了，估计没适配

**Comment by sproblvem** [comment]
两位，我今天也遇到了相似的问题。我这边是因为没有提前安装im-select以及配置项写的不对，写对之后就work了。
系统：Version 14.1.1 (23B81)
芯片：Apple M2 Pro
Obsidian：Version 1.4.16 (Installer 1.4.16)
配置项如下：
Input Method Name
	com.apple.keylayout.ABC
Obtaining Command
	/opt/homebrew/Cellar/im-select/1.0.1/bin/im-select
Switching Command
	/opt/homebrew/Cellar/im-select/1.0.1/bin/im-select {im}

**Comment by matyle** [comment]
<img width="541" alt="image" src="https://github.com/ALONELUR/vim-im-select-obsidian/assets/27877040/01efe49f-496f-4e4d-99f3-92bb779e5728">
打开开发窗口一眼就看到了问题所在

**Comment by ALONELUR** [comment]
配置的问题，按照推荐配置写就行
