### ISSUE TITLE
插件在Obsidian1.5版本更新后失效

### ISSUE THREAD

**Issue by ZI2104** [ALONELUR/vim-im-select-obsidian#24]
1.5public版本提到："文件资源管理器”和“标记”窗格都收到了一个小的代码重构。这可能会影响一些依赖于内部 JS 结构的插件。  
同时VSCode内im-select可正常使用
插件需要更新

**Comment by laphylee** [comment]
I've also encountered this issue.

**Comment by qazxcdswe123** [comment]
https://github.com/qazxcdswe123/vim-im-select-obsidian/releases/tag/1.5.3

在作者修改之前，可以替换插件文件夹下的main.js，暂时用着还没出问题

**Comment by yizhenAllen** [comment]
> https://github.com/qazxcdswe123/vim-im-select-obsidian/releases/tag/1.5.3
> 
> 在作者修改之前，可以替换插件文件夹下的main.js，暂时用着还没出问题

有效的

**Comment by TaylorTrz** [comment]
> https://github.com/qazxcdswe123/vim-im-select-obsidian/releases/tag/1.5.3
> 
> 在作者修改之前，可以替换插件文件夹下的main.js，暂时用着还没出问题

好使，赞
