### ISSUE TITLE
Version 1.5.3 seems to break the plugin

### ISSUE THREAD

**Issue by RobberFox** [ALONELUR/vim-im-select-obsidian#26]
The plugin works in 1.4.16 as intended, but in 1.5.3 it stops working completely (probably due to code refactoring by the obsidian developers)

**Comment by eluck** [comment]
It's very likely that CodeMirror version is not identified properly:

<img width="1314" alt="image" src="https://github.com/ALONELUR/vim-im-select-obsidian/assets/3399956/769effa0-1cac-4138-8a89-d20fa9f95f4a">

**Comment by eluck** [comment]
I managed to get it working by forcing version 6 of CodeMirror:

<img width="1317" alt="image" src="https://github.com/ALONELUR/vim-im-select-obsidian/assets/3399956/da817964-879a-47cb-93e7-dffbc980fdb8">

**Comment by eluck** [comment]
Hm..
here's a pull request with the fix: https://github.com/ALONELUR/vim-im-select-obsidian/pull/25
🤦

**Comment by qazxcdswe123** [comment]
before the original author merge this fix, you can fix it manually by substituting the main.js file in the plugin folder with https://github.com/qazxcdswe123/vim-im-select-obsidian/releases/tag/1.5.3

**Comment by shuxin1988** [comment]
> before the original author merge this fix, you can fix it manually by substituting the main.js file in the plugin folder with https://github.com/qazxcdswe123/vim-im-select-obsidian/releases/tag/1.5.3

this works,Thanks!

**Comment by j412l3kj** [comment]
> before the original author merge this fix, you can fix it manually by substituting the main.js file in the plugin folder with https://github.com/qazxcdswe123/vim-im-select-obsidian/releases/tag/1.5.3

That really works, thank you so much!
