### ISSUE TITLE
windows中不起作用

### ISSUE THREAD

**Issue by ziyuanjun** [ALONELUR/vim-im-select-obsidian#3]
# 版本：
obsidian 版本：0.13.19
vim select版本：0.1.0
win10 64位
im-select.exe 可在命令行中正常切换输入法。

# 插件设置：
![image](https://user-images.githubusercontent.com/10259127/148885689-0992ed84-7319-44a0-9b99-cd3605ceaa5c.png)

# 问题：
normal 模式下不自动切换为英文输入法

**Comment by ALONELUR** [comment]
这是之前代码遗留的一个BUG，这两天会更新0.1.1版本修复这个问题。

**Comment by ALONELUR** [comment]
新的0.1.1版本已经修复了这个问题，如果还有问题就再回复这个issue :smile:

**Comment by ziyuanjun** [comment]
试了一下，可以正常切换到normal模式了
