### ISSUE TITLE
vim-im-select-obsidian偶尔失效问题及临时解决方案

### ISSUE THREAD

**Issue by Drunk-Dream** [ALONELUR/vim-im-select-obsidian#31]
# vim-im-select-obsidian偶尔失效问题及临时解决方案

## 版本 Version

obsidian version: 1.7.7
imselect version: 0.2.0

## 问题描述 Description

当使用obsidian文件列表左键单击在当前标签页打开新的文件时，会出现im-selsct失效的问题。而如果使用快捷键`Ctrl+o`打开文件或者打开到新标签页的时候则没有这个问题。

>When you left-click on a file in the Obsidian file list to open a new file in the current tab, there will be an issue with im-selsct failing. However, if you use the shortcut key `Ctrl+o` to open a file or open it in a new tab, this problem does not occur.

## 问题追踪 Trace

使用devtool追踪发现当左键单击在当前标签页打开时，以从test1文件打开到test2文件为例，此时`getActiveView()`函数获取的`view`中的`data`属性仍然还是test1，这时候编辑器窗口应该还是旧的窗口，因此监听函数并没有新增到新的编辑器上。这就造成新编辑器中没有相应的监听事件。
如下图所示，我首先打开test1文件，然后左键直接在当前标签页打开新的test2文件，此时获得的`view.data`仍然还是test1

>Using devtool to track and find that when the left-click opens in the current tab, take the file from test1 to test2 as an example. At this time, the `data` attribute in the `view` obtained by the `getActivity()` function is still test1. At this time, the editor window should still be the old window, so the listener function does not have added to a new editor. This results in no corresponding listening events in the new editor. 
>As shown in the figure below, I first open the test1 file, and then left-click to open the new test2 file directly in the current tab. At this time, I get the `view.data` is still test1

![Pasted image 20241119151715](https://github.com/user-attachments/assets/d95a84c7-b4bb-4738-a8a4-d0d8913eedb1)

## 解决方案 Solution

我认为该问题是obsidian本身的bug，因此提供以下两种临时解决方案：
>I believe this issue is a bug in Obsidian itself, so I provide the following two temporary solutions:
1. 使用`Ctrl+o`打开文件，如果要使用文件列表，请使用鼠标中键或`Ctrl`+左键打开新标签页
   >Use `Ctrl+o` to open a file. If you want to use the file list, please use the middle mouse button or `Ctrl`+left mouse button to open a new tab
2. 修改监听函数，将监听条件从`file-open`修改为`active-leaf-change`，如下图所示。   同时该方案还可以解决左右分屏或上下分屏时失效的问题。但该方案也有一些问题，就是每次切换窗口都会重新注入一次监听函数，可能会造成不必要的性能损失。
      ![Pasted image 20241119152405](https://github.com/user-attachments/assets/4879511b-7297-41fe-95f5-469970d93e83)
   >Modify the listening function, changing the listening condition from `file-open` to `active-leaf-change`, as shown in the figure below. The scheme can also solve the problem of failure when splitting the screen horizontally or vertically. However, the scheme also has some issues, such as the need to re-inject the listening function each time the window is switched, which may cause unnecessary performance loss.

**Comment by DEAN-Cherry** [comment]
感谢，终于让我搞明白了为什么有时生效有时失效。
