### ISSUE TITLE
在Linux下有点问题

### ISSUE THREAD

**Issue by free-150** [ALONELUR/vim-im-select-obsidian#4]
设置如下：  
<br/>
![图片](https://user-images.githubusercontent.com/92285544/155481421-cd7b2d0a-f779-4703-9e73-96fb0e9cf2b0.png)  
<br/>
`插入模式`后是中文输入法但当此时用`Ctrl+Space`切换后再按`Esc` 无法回到`普通模式`了。   
mac下没有这问题。[ vim-im-select-obsidian](https://github.com/yuanotes/obsidian-vim-im-switch-plugin)也没有这个问题但不支持CM6。

**Comment by ALONELUR** [comment]
对不起一直没看到消息😣
我今天晚些会检查相关功能后回复你。
你说的无法回到`普通模式`是指现在obsidian的vim-mode不正常吗？

**Comment by cherrot** [comment]
Defaut IM: `keyboard-us`
Obtaining Command:

```bash
[[ `/usr/bin/fcitx5-remote` == 2 ]] && echo pinyin || echo keyboard-us
```

Switching Command:
```bash
/usr/bin/fcitx5-remote -s {im}
```

**Comment by ALONELUR** [comment]
请参照@cherrot给出的设置进行尝试。
