### ISSUE TITLE
可否记住输入法状态？

### ISSUE THREAD

**Issue by lazureice** [ALONELUR/vim-im-select-obsidian#5]
回到 insert 模式时，会切换成中文。
是否可以实现，如果原来就是英文，依然保持英文状态？

使用的是win10微软拼音输入法。

**Comment by ALONELUR** [comment]
这个插件的想实现的效果是，如果你在insert模式下是什么输入法，返回到normal模式会为你切换纯英文输入法，方便你在normal模式下可以使用各个快捷键，不受你在insert模式下使用非英文输入法的影响。
目前我尝试的：
- 在insert模式下使用英文输入法，切换为normal变为英文，在回到insert还是英文。
- 在insert模式下使用中文输入法，切换为normal变为英文，在回到insert还是中文。

你看这样使用满足你的需求吗？

**Comment by lazureice** [comment]
感谢回复。
因为我习惯用 shift 切换为中文输入法的英文，而不是 win+space 切换为英文输入法。
不过不重要。这样也可以。

**Comment by ALONELUR** [comment]
🙇‍
因为在win10下，通过微软输入法shift切换的中英文输入在外部看起来它们是同一个输入法，因此目前都是使用一个纯英输入法和一个中文输入法，这样才能通过切换输入法实现中英切换。

**Comment by lazureice** [comment]
原来如此。又是 win 的问题。
