### ISSUE TITLE
路径配置支持相对路径

### ISSUE THREAD

**Issue by CoolLiuzw** [ALONELUR/vim-im-select-obsidian#7]
首先，表示软件很不错，解决也重复性切换输入法问题，是我需要的软件。

目前，主要是有多台PC同步需求，im-select.exe放置obsidian文件中，im-select 一起同步
现在只能配置绝对路径，每台电脑的im-select.exe的路径可能不同
需要支持配置 obsidian 目录的相对路径 im-select.exe 的路径

**Comment by ALONELUR** [comment]
好的，我尝试添加这个功能🤗

**Comment by ALONELUR** [comment]
> 首先，表示软件很不错，解决也重复性切换输入法问题，是我需要的软件。
> 
> 目前，主要是有多台PC同步需求，im-select.exe放置obsidian文件中，im-select 一起同步 现在只能配置绝对路径，每台电脑的im-select.exe的路径可能不同 需要支持配置 obsidian 目录的相对路径 im-select.exe 的路径

你好，我调查了一下，如果加上解析相对路径的功能反而降低了插件配置的适用性。
你可以选择这样的解决办法，在不同的电脑上配置PATH环境变量，添加im-select所在目录。
之后在插件配置中直接输入im-select，而不是输入其所在的路径，就可实现你的你需要的效果了。

**Comment by CoolLiuzw** [comment]
> > 首先，表示软件很不错，解决也重复性切换输入法问题，是我需要的软件。
> > 目前，主要是有多台PC同步需求，im-select.exe放置obsidian文件中，im-select 一起同步 现在只能配置绝对路径，每台电脑的im-select.exe的路径可能不同 需要支持配置 obsidian 目录的相对路径 im-select.exe 的路径
> 
> 你好，我调查了一下，如果加上解析相对路径的功能反而降低了插件配置的适用性。 你可以选择这样的解决办法，在不同的电脑上配置PATH环境变量，添加im-select所在目录。 之后在插件配置中直接输入im-select，而不是输入其所在的路径，就可实现你的你需要的效果了。

好的，是一个不错的方法，谢谢
