### ISSUE TITLE
MacOS CM6下Live Preview中 fcitx-remote失效，以及切换逻辑问题

### ISSUE THREAD

**Issue by Palvehelmed** [ALONELUR/vim-im-select-obsidian#8]
1. 在CM6下Live Preview中 fcitx-remote 失效，详见[这里](https://github.com/yuanotes/obsidian-vim-im-switch-plugin/issues/5#issuecomment-1016040019)，希望example可以改成`im-select`，对新用户更友好些；
2. 没有太明白使用逻辑，在Insert mode中使用`A输入法`，切到Normal Mode为`英文输入法`，逻辑是切回Insert还是保持`英文`？是否切回能够保持`A输入法`更好？

附上我的配置：

Default IM: `com.apple.keylayout.US`
Obtaining Command: `/usr/local/bin/im-select`
Switching Command: `/usr/local/bin/im-select {im}`

**Comment by ALONELUR** [comment]
目前插件的逻辑是这样的：
Default IM应该填入`Normal`模式下你需要使用的输入法

这样的话，插件会这么工作：在从`INSERT`模式离开时会获得当前用户使用的输入法，同时切换为Default IM。
重新进入`INSERT`的时候重新切换到上次使用的输入法。

不知道这样是否解决你的问题。

**Comment by ALONELUR** [comment]
CM6我应该已经对其做了适配，不过我没有MAC系统的电脑，所以可以在详细描述一下失效的部分嘛？

**Comment by lclrc** [comment]
> CM6我应该已经对其做了适配，不过我没有MAC系统的电脑，所以可以在详细描述一下失效的部分嘛？

试了试用`macism`切换的话暂时没发现什么问题, 感谢适配live preview!

**Comment by ALONELUR** [comment]
😁

**Comment by betterZCH** [comment]
> `/usr/local/bin/`

可以看一下你的命令吗？我也用的macism，但是一直不生效
