### ISSUE TITLE
window下设置

### ISSUE THREAD

**Issue by zhongxufeng** [ALONELUR/vim-im-select-obsidian#9]
第三栏应该填入：
C:\im-select.exe {im} && C:\\im-select\\im-select.exe 2052
![image](https://user-images.githubusercontent.com/93416022/171542915-6a0e006e-9c1e-4bb0-bd86-2ad037bcf44d.png)

**Comment by ALONELUR** [comment]
第三栏的如果插件工作正常应该只需要`C:\im-select.exe {im}` （第一部分是可执行文件）
附上我的配置
![image](https://user-images.githubusercontent.com/46865464/171545925-6ef68054-60d0-4660-8e8f-ff9a0e9032d2.png)

检查一下im-select的路径是否正确？

**Comment by zhongxufeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhongxufeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
